#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home_index:
  path: /
  controller: App\Controller\HomeController::index
  methods: GET

home_new:
  path: /new
  controller: App\Controller\HomeController::new
  methods: GET
